services:
  frontend:
    build: .
    container_name: smart-ui
    ports:
      - "5456:3000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=5456
    restart: always
